FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Controllers/BeneficiarioController.cs
using FI.AtividadeEntrevista.BLL;
using WebAtividadeEntrevista.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FI.AtividadeEntrevista.DML;
using System.Web.Http.Results;

namespace WebAtividadeEntrevista.Controllers
{
    public class BeneficiarioController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BeneficiarioList(long ClienteId)
        {
            BoBeneficiario bo = new BoBeneficiario();
            List<Beneficiario> Beneficiarios = bo.ListarBeneficiarios(ClienteId);
            List<BeneficiarioModel> model = new List<BeneficiarioModel>();

            if (Beneficiarios != null || Beneficiarios.Any())
            {
                foreach (var beneficiario in Beneficiarios)
                {
                    model.Add(new List<BeneficiarioModel>
                    {
                        new BeneficiarioModel
                        {
                            Id = beneficiario.Id,
                            IdCliente = beneficiario.IdCliente,
                            NomeBeneficiario = beneficiario.Nome,
                            CpfBeneficiario = beneficiario.Cpf
                    } }.First());
                }
            }

            return Json(new { Result = "OK", Records = model, TotalRecordCount = model.Count });
        }

        [HttpPost]
        public JsonResult Excluir(int id)
        {
            try
            {
                BoBeneficiario bo = new BoBeneficiario();

                bo.Excluir(id);

                //Return result to jTable
                return Json("Excluido com sucesso");
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Controllers/ClienteController.cs
using FI.AtividadeEntrevista.BLL;
using WebAtividadeEntrevista.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FI.AtividadeEntrevista.DML;
using System.Web.Http.Results;

namespace WebAtividadeEntrevista.Controllers
{
    public class ClienteController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Incluir(ClienteModel model)
        {
            BoCliente bo = new BoCliente();
            BoBeneficiario bnf = new BoBeneficiario();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else if (bo.VerificarExistencia(model.Cpf))
            {
                Response.StatusCode = 400;
                return Json("CPF já cadastrado alteriormente");
            }
            else if (!bo.ValidaCpfCpf(model.Cpf))
            {
                Response.StatusCode = 400;
                return Json("CPF inválido");
            }
            else
            {

                model.Id = bo.Incluir(new Cliente()
                {
                    CEP = model.CEP,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone,
                    Cpf = model.Cpf
                });

                foreach (var beneficiario in model.Beneficiarios)
                {
                    bnf.Incluir(new List<Beneficiario>
                    {
                        new Beneficiario
                        {
                            Cpf = beneficiario.CpfBeneficiario,
                            IdCliente = model.Id,
                            Nome = beneficiario.NomeBeneficiario
                        }
                    });
                }

                return Json("Cadastro efetuado com sucesso");
            }
        }

        [HttpPost]
        public JsonResult Alterar(ClienteModel model)
        {
            BoCliente bo = new BoCliente();
            BoBeneficiario bnf = new BoBeneficiario();

            if (!this.ModelState.IsValid)
            {
                List<string> erros = (from item in ModelState.Values
                                      from error in item.Errors
                                      select error.ErrorMessage).ToList();

                Response.StatusCode = 400;
                return Json(string.Join(Environment.NewLine, erros));
            }
            else if (!bo.ValidaCpfCpf(model.Cpf))
            {
                Response.StatusCode = 400;
                return Json("CPF inválido");
            }
            else
            {
                bo.Alterar(new Cliente()
                {
                    Id = model.Id,
                    CEP = model.CEP,
                    Cidade = model.Cidade,
                    Email = model.Email,
                    Estado = model.Estado,
                    Logradouro = model.Logradouro,
                    Nacionalidade = model.Nacionalidade,
                    Nome = model.Nome,
                    Sobrenome = model.Sobrenome,
                    Telefone = model.Telefone,
                    Cpf = model.Cpf
                });

                foreach (var beneficiario in model.Beneficiarios)
                {
                    bnf.Incluir(new List<Beneficiario>
                    {
                        new Beneficiario
                        {
                            Cpf = beneficiario.CpfBeneficiario,
                            IdCliente = model.Id,
                            Nome = beneficiario.NomeBeneficiario
                        }
                    });
                }

                return Json("Cadastro alterado com sucesso");
            }
        }

        [HttpGet]
        public ActionResult Alterar(long id)
        {
            BoCliente bo = new BoCliente();
            Cliente cliente = bo.Consultar(id);
            Models.ClienteModel model = null;

            if (cliente != null)
            {
                model = new ClienteModel()
                {
                    Id = cliente.Id,
                    CEP = cliente.CEP,
                    Cidade = cliente.Cidade,
                    Email = cliente.Email,
                    Estado = cliente.Estado,
                    Logradouro = cliente.Logradouro,
                    Nacionalidade = cliente.Nacionalidade,
                    Nome = cliente.Nome,
                    Sobrenome = cliente.Sobrenome,
                    Telefone = cliente.Telefone,
                    Cpf = cliente.Cpf
                };


            }

            return View(model);
        }

        [HttpPost]
        public JsonResult ClienteList(int jtStartIndex = 0, int jtPageSize = 0, string jtSorting = null)
        {
            try
            {
                int qtd = 0;
                string campo = string.Empty;
                string crescente = string.Empty;
                string[] array = jtSorting.Split(' ');

                if (array.Length > 0)
                    campo = array[0];

                if (array.Length > 1)
                    crescente = array[1];

                List<Cliente> clientes = new BoCliente().Pesquisa(jtStartIndex, jtPageSize, campo, crescente.Equals("ASC", StringComparison.InvariantCultureIgnoreCase), out qtd);

                //Return result to jTable
                return Json(new { Result = "OK", Records = clientes, TotalRecordCount = qtd });
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }
    }
}

FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Alterar.cshtml
@model WebAtividadeEntrevista.Models.ClienteModel
@{
    ViewBag.Title = "Alterar Cliente";
}
@section scripts{
    <script>
        var clienteId = @Model.Id
        var urlPost = '@Url.Action("Alterar", "Cliente", new { area = "" })';
        var obj = @Html.Raw(Json.Encode(Model));
        var urlRetorno = '@Url.Action("Index", "Cliente", new { area = "" })';
        var urlBeneficiarioList = '@Url.Action("BeneficiarioList", "Beneficiario", new { area = "" })';
        var urlExclusao = '@Url.Action("Excluir", "Beneficiario", new { area = "" })';
    </script>
    @Scripts.Render("~/bundles/altClientes")
    @Scripts.Render("~/bundles/beneficiario")
    @Scripts.Render("~/bundles/listBeneficiarios")
    @Scripts.Render("~/bundles/inputmask")

}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Forms.cshtml
<form id="formCadastro" method="post">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nome">Nome:</label>
                <input required="required" type="text" class="form-control" id="Nome" name="Nome" placeholder="Ex.: João" maxlength="50">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Sobrenome">Sobrenome:</label>
                <input required="required" type="text" class="form-control" id="Sobrenome" name="Sobrenome" placeholder="Ex.: da Silva" maxlength="255">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Cpf">CPF:</label>
                <input required="required" type="text" class="form-control" id="Cpf" name="Cpf" onfocusout="validaCpf(document.getElementById('Cpf').value);" placeholder="Ex: 999.999.999-99" maxlength="14">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Nacionalidade">Nacionalidade:</label>
                <input required="required" type="text" class="form-control" id="Nacionalidade" name="Nacionalidade" placeholder="Ex.: brasileira" maxlength="50">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="CEP">CEP:</label>
                <input required="required" type="text" class="form-control" id="CEP" name="CEP" placeholder="Ex.: 01011-100" maxlength="9">
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Estado">Estado:</label>
                <select required="required" id="Estado" class="form-control" name="Estado">
                    <option value="">Selecione</option>
                    <option value="SP">São Paulo</option>
                    <option value="PE">Pernambuco</option>
                </select>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label for="Cidade">Cidade:</label>
                <input required="required" type="text" class="form-control" id="Cidade" name="Cidade" maxlength="50" placeholder="Ex.: São Paulo">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label for="Logradouro">Logradouro:</label>
                <input required="required" type="text" class="form-control" id="Logradouro" name="Logradouro" placeholder="Ex.: Rua Boa Vista 253" maxlength="500">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="Email">E-mail:</label>
                <input required="required" type="text" class="form-control" id="Email" name="Email" placeholder="Ex.: email@email.com" maxlength="2079">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="Telefone">Telefone:</label>
                <input required="required" type="tel" class="form-control" id="Telefone" name="Telefone" placeholder="Ex.: (11) 2020-3030" maxlength="15">
            </div>
        </div>
    </div>
    <div class="col-md-12" style="display: none;">
        <div class="form-group">
            <input type="number" class="form-control" id="ClienteId" name="ClienteId" maxlength="15" value="@Model?.Id">
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="pull-left">
                <button type="button" class="btn btn-sm btn-default" data-toggle="modal" data-target="#ModalBeneficiarios">Beneficiários</button>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="pull-right">
                <button type="submit" class="btn btn-sm btn-success">Salvar</button>
                @Html.ActionLink("Voltar", "Index", "Cliente", new { }, new { @class = "btn btn-sm btn-danger" })
            </div>
        </div>
    </div>

</form>

<!-- Modal -->
<div id="ModalBeneficiarios" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Beneficiários</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="CpfBeneficiario">CPF:</label>
                            <input required="required" type="text" class="form-control" id="CpfBeneficiario"  name="CpfBeneficiario" onfocusout="validaCpf(document.getElementById('CpfBeneficiario').value);" placeholder="Ex: 999.999.999-99" maxlength="14">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="NomeBeneficiario">Nome:</label>
                            <input required="required" type="text" class="form-control" id="NomeBeneficiario" name="NomeBeneficiario"  placeholder="Ex.: João Da Silva" maxlength="250">
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="pull-right form-group">
                            <label for="Nome" style="color: transparent;">Incluir</label>
                            <button onclick="adicionarBeneficiarioAoGrid()" class="btn btn-sm btn-success">Incluir</button>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div id="gridBeneficiarios"></div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Incluir.cshtml
@model WebAtividadeEntrevista.Models.ClienteModel
@{
    ViewBag.Title = "Cadastrar Cliente";
}
@section scripts{
    <script>
        var clienteId = 0
        var urlPost = '@Url.Action("Incluir", "Cliente", new { area = "" })';
        var urlPostBeneficiario = '@Url.Action("Incluir", "Beneficiario", new { area = "" })';
        var urlBeneficiarioList = '@Url.Action("BeneficiarioList", "Beneficiario", new { area = "" })';

    </script>
    @Scripts.Render("~/bundles/clientes")
    @Scripts.Render("~/bundles/beneficiario")
    @Scripts.Render("~/bundles/listBeneficiarios")
    @Scripts.Render("~/bundles/inputmask")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.Partial("Forms")

FI.WebAtividadeEntrevista/FI.WebAtividadeEntrevista/Views/Cliente/Index.cshtml
@{
    ViewBag.Title = "Clientes";
}
@section scripts{
<script>
    var urlAlteracao = '@Url.Action("Alterar", "Cliente", new { area = "" })';
    var urlClienteList = '@Url.Action("ClienteList", "Cliente", new { area = "" })';

</script>
    @Scripts.Render("~/bundles/listClientes")
}
<h2>@Html.Raw(ViewBag.Title)</h2>
@Html.ActionLink("Novo Cliente", "Incluir", "Cliente", new { }, new { @class= "btn btn-sm btn-primary pull-right" })
<table id="gridClientes" class="table"></table>